ev_front_homepage:
    path:     /
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_events:
    path: /prochains-evenements
    defaults: { _controller: EvFrontBundle:Default:next }

ev_front_accueil_connected:
    path: /accueil/connected
    defaults: { _controller: EvFrontBundle:Default:connected }
    
ev_front_register:
    path: /register
    defaults: { _controller: EvUserBundle:Registration:register }

ev_front_best:
    path: /meilleures-ventes
    defaults: { _controller: EvFrontBundle:Default:best }
    
ev_front_register_event:
    path: /register_event/{idEvent}/{idUser}
    defaults: { _controller: EvFrontBundle:Default:registerEvent }