ev_front_homepage:
    path:     /
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_events:
    path: /prochains-evenements
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_accueil_connected:
    path: /accueil/connected
    defaults: { _controller: EvFrontBundle:Default:connected }
    
ev_front_register:
    path: /register
    defaults: { _controller: EvUserBundle:Registration:register }