ev_front_homepage:
    path:     /
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_events:
    path: /prochains-evenements
    defaults: { _controller: EvFrontBundle:Default:next }

ev_front_connexion:
    path: /connexion
    defaults: { _controller: EvFrontBundle:Default:connexion }
    
ev_front_best:
    path: /meilleures-ventes
    defaults: { _controller: EvFrontBundle:Default:best }
