ev_front_homepage:
    path:     /
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_events:
    path: /prochains-evenements
    defaults: { _controller: EvFrontBundle:Default:index }

ev_front_connexion:
    path: /connexion
    defaults: { _controller: EvFrontBundle:Default:connexion }
    
ev_front_register:
    path: /register
    defaults: { _controller: EvUserBundle:Registration:register }