<?php

namespace Ev\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlertsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertsRepository extends EntityRepository
{
}
