<?php

namespace Ev\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findOneNameById($id)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT c.nom FROM EvFrontBundle:Category c WHERE c.id = :id')
                ->setParameter('id', $id)
                ->getResult();
    }
}
