<?php

namespace Ev\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ImagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesRepository extends EntityRepository
{
    public function findOneById($id)
    {
        return $this->getEntityManager()
                ->createQuery('SELECT i FROM EvFrontBundle:Images i WHERE i.id = :id')
                ->setParameter('id', $id)
                ->getResult();
    }
}
