<?php

namespace Ev\FrontBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitsRepository extends EntityRepository
{
    public function findOneById($id)
    {
        $q = $this->getEntityManager()
                ->createQuery('SELECT p FROM EvFrontBundle:Produits p WHERE p.id = :id')
                ->setParameter('id', $id)
                ->getResult();
        
        return $q[0];
    }
}
